# 敏感信息
EMAIL_ADDRESS=wxb1@h-sun.com
EMAIL_PASSWORD=496795ef2tsWaJol

# 服务器配置
EMAIL_IMAP_SERVER=p220s.chinaemail.cn
EMAIL_IMAP_PORT=993
EMAIL_USE_SSL=True

# 规则文件路径
EMAIL_RULES_FILE=config/email_rules.yaml

# 爬虫网站信息
# 和舰科技
HJTC_USERNAME=HUX_LEIHJ
HJTC_PASSWORD=UNBfg-241113
HJTC_OUTPUT_DIR=downloads/pending/晶圆进度表/和舰科技

# 江苏芯丰
XINF_USERNAME=314
XINF_PASSWORD=68241373
XINF_OUTPUT_DIR=downloads/pending/封装进度表/江苏芯丰

# 长电科技
JCET_USERNAME=A2-099
JCET_PASSWORD=Tel68241373$
JCET_OUTPUT_DIR=downloads/pending/WIP/长电科技

# 数据库配置
DB_USER=sa
DB_PASSWORD=P@ssw0rd
DB_HOST=192.168.200.21
DB_DATABASE=E10
DB_DRIVER=ODBC Driver 18 for SQL Server
DB_POOL_SIZE=5
DB_MAX_OVERFLOW=10
DB_POOL_TIMEOUT=30
DB_POOL_RECYCLE=3600
DB_ECHO=False
